FROM nginx:1.27.2
RUN apt-get update && apt-get -y upgrade
RUN  groupadd -r juan && \
     useradd -r -g juan juan
RUN chown -R juan:juan /usr/share/nginx/html
USER juan 


CMD [ "bash","-c", "echo Hello from appuser!" ]